spring:
  application:
    name: web-pet-project
  datasource:
    url: jdbc:postgresql://localhost:5432/a.tsvaeva
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /api/v1

settings:
  operation:
    get-users:
      default-limit: 2